from _typeshed import Incomplete

def Encode(string, encoding: Incomplete | None = None): ...
def Decode(data, encoding: Incomplete | None = None): ...
def GetEncodedValue(env, name, default: Incomplete | None = None): ...
def SetEncodedValue(env, name, value, encoding: Incomplete | None = None) -> None: ...
def EncodeEnv(env, encoding: Incomplete | None = None): ...
