---

# Create an environment called pypi
# https://github.com/Josef-Friedrich/<repo>/settings/environments

# Create a new trusted publisher
# https://pypi.org/manage/project/<name>/settings/publishing/

# https://medium.com/@nipunweerasiri/publishing-python-packages-to-pypi-using-uv-and-github-workflows-with-trusted-publishing-47bdfab162db
# https://docs.pypi.org/trusted-publishers/
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/


name: Build and Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout git repository
        uses: actions/checkout@v4

      # https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-groups

      - name: Build wheel
        run: uv build

      - name: Publish package
        run: uv publish
