---
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

      # https://docs.astral.sh/uv/guides/integration/github/#multiple-python-versions
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      # https://github.com/ymyzk/tox-gh-actions
      - name: Run tox targets for ${{ matrix.python-version }}
        run: uv run pytest tests
